"""Tool registry contracts for deep literature research agents."""
from __future__ import annotations

from typing import Any

from .models import ToolSpec


PAPER_FIELDS = (
    "paperId,externalIds,url,title,abstract,year,publicationDate,authors,venue,"
    "publicationTypes,citationCount,influentialCitationCount,referenceCount,"
    "fieldsOfStudy,s2FieldsOfStudy,tldr,openAccessPdf"
)
PAPER_FIELDS_WITH_EMBEDDING = f"{PAPER_FIELDS},embedding.specter_v2"


def _schema(properties: dict[str, Any], required: list[str]) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": properties,
        "required": required,
        "additionalProperties": False,
    }


def _paper_array_output(name: str) -> dict[str, Any]:
    return _schema(
        {
            name: {"type": "array", "items": {"type": "object"}},
            "total": {"type": ["integer", "null"]},
            "next_token": {"type": ["string", "null"]},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
        [name],
    )


def _tool(
    *,
    name: str,
    category: str,
    purpose: str,
    input_schema: dict[str, Any],
    output_schema: dict[str, Any],
    endpoint: str | None = None,
    input_example: dict[str, Any] | None = None,
    output_example: dict[str, Any] | None = None,
    reads: list[str] | None = None,
    writes: list[str] | None = None,
    fallback_tools: list[str] | None = None,
    notes: list[str] | None = None,
) -> ToolSpec:
    return ToolSpec(
        name=name,
        category=category,
        purpose=purpose,
        endpoint=endpoint,
        input_schema=input_schema,
        output_schema=output_schema,
        input_example=input_example or {},
        output_example=output_example or {},
        reads=reads or [],
        writes=writes or [],
        fallback_tools=fallback_tools or [],
        notes=notes or [],
    )


def build_default_tool_registry() -> dict[str, ToolSpec]:
    """Return the shared tool surface every research agent may use.

    These are contracts, not network implementations. Concrete Semantic Scholar,
    SerpApi, filesystem, and derived-analysis tools should conform to these
    schemas so prompts and orchestrator code stay stable.
    """

    specs = [
        _tool(
            name="resolve_arxiv_paper",
            category="semantic_scholar.graph",
            purpose="Resolve an arXiv URL/id to canonical Semantic Scholar metadata.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/{paper_id}",
            input_schema=_schema(
                {
                    "arxiv_url": {"type": "string"},
                    "fields": {"type": "string", "default": PAPER_FIELDS},
                },
                ["arxiv_url"],
            ),
            output_schema=_schema(
                {
                    "paper": {"type": "object"},
                    "canonical_paper_id": {"type": "string"},
                    "warnings": {"type": "array", "items": {"type": "string"}},
                },
                ["paper", "canonical_paper_id"],
            ),
            input_example={"arxiv_url": "https://arxiv.org/abs/1706.03762", "fields": PAPER_FIELDS},
            output_example={"canonical_paper_id": "204e3073870fae3d05bcbc2f6a8e263d9b72e776"},
            reads=["Semantic Scholar paper details"],
            fallback_tools=["paper_relevance_search", "paper_autocomplete"],
            notes=[
                "Parse arXiv IDs as ARXIV:<id> first.",
                "Store the canonical paperId for all graph traversal.",
            ],
        ),
        _tool(
            name="get_paper_metadata",
            category="semantic_scholar.graph",
            purpose="Fetch structured metadata for any known paper identifier.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/{paper_id}",
            input_schema=_schema({"paper_id": {"type": "string"}, "fields": {"type": "string", "default": PAPER_FIELDS}}, ["paper_id"]),
            output_schema=_schema({"paper": {"type": "object"}, "warnings": {"type": "array", "items": {"type": "string"}}}, ["paper"]),
            input_example={"paper_id": "ARXIV:1706.03762", "fields": PAPER_FIELDS},
            output_example={"paper": {"paperId": "...", "title": "Attention is All you Need", "year": 2017}},
            reads=["Semantic Scholar paper details"],
        ),
        _tool(
            name="get_paper_tldr",
            category="semantic_scholar.graph",
            purpose="Fetch Semantic Scholar TLDR summary when available.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/{paper_id}?fields=tldr,title",
            input_schema=_schema({"paper_id": {"type": "string"}}, ["paper_id"]),
            output_schema=_schema({"paper_id": {"type": "string"}, "title": {"type": ["string", "null"]}, "tldr": {"type": ["object", "null"]}}, ["paper_id"]),
            input_example={"paper_id": "ARXIV:1706.03762"},
            output_example={"paper_id": "...", "tldr": {"text": "A transformer architecture for sequence transduction."}},
            reads=["Semantic Scholar paper details"],
            notes=["TLDR is useful orientation, not ground truth."],
        ),
        _tool(
            name="get_paper_embedding",
            category="semantic_scholar.graph",
            purpose="Fetch a paper-level SPECTER2 embedding for similarity reranking.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/{paper_id}?fields=embedding.specter_v2",
            input_schema=_schema({"paper_id": {"type": "string"}}, ["paper_id"]),
            output_schema=_schema({"paper_id": {"type": "string"}, "embedding": {"type": ["object", "null"]}}, ["paper_id", "embedding"]),
            input_example={"paper_id": "ARXIV:1706.03762"},
            output_example={"paper_id": "...", "embedding": {"model": "specter_v2", "vector": [0.01, -0.02]}},
            reads=["Semantic Scholar paper details"],
            notes=["Use as a reranking signal after candidate generation, not as the only discovery step."],
        ),
        _tool(
            name="get_references",
            category="semantic_scholar.graph",
            purpose="Fetch papers cited by the seed or candidate paper.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/{paper_id}/references",
            input_schema=_schema(
                {
                    "paper_id": {"type": "string"},
                    "limit": {"type": "integer"},
                    "offset": {"type": "integer"},
                    "fields": {"type": "string"},
                },
                ["paper_id"],
            ),
            output_schema=_paper_array_output("references"),
            input_example={"paper_id": "ARXIV:1706.03762", "limit": 100, "fields": "citedPaper.paperId,citedPaper.title,citedPaper.year,citedPaper.abstract,citedPaper.citationCount"},
            output_example={"references": [{"citedPaper": {"paperId": "...", "title": "Neural Machine Translation by Jointly Learning to Align and Translate"}}]},
            reads=["Semantic Scholar references"],
            fallback_tools=["paper_bulk_search", "paper_relevance_search"],
        ),
        _tool(
            name="get_high_impact_references",
            category="derived_literature",
            purpose="Rank references by citation and influential-citation signals.",
            input_schema=_schema({"paper_id": {"type": "string"}, "limit": {"type": "integer"}}, ["paper_id"]),
            output_schema=_paper_array_output("references"),
            input_example={"paper_id": "ARXIV:1706.03762", "limit": 25},
            output_example={"references": [{"paperId": "...", "score_reason": "high citationCount and influentialCitationCount"}]},
            reads=["get_references"],
            fallback_tools=["get_references"],
            notes=["Good for foundational background, not sufficient for closest-prior-work claims."],
        ),
        _tool(
            name="get_recent_references",
            category="derived_literature",
            purpose="Find near-publication references likely to be closest contemporaneous prior work.",
            input_schema=_schema({"paper_id": {"type": "string"}, "seed_year": {"type": "integer"}, "window_years": {"type": "integer"}, "limit": {"type": "integer"}}, ["paper_id", "seed_year"]),
            output_schema=_paper_array_output("references"),
            input_example={"paper_id": "ARXIV:1706.03762", "seed_year": 2017, "window_years": 3, "limit": 25},
            output_example={"references": [{"paperId": "...", "year": 2016}]},
            reads=["get_references"],
        ),
        _tool(
            name="get_reference_graph_summary",
            category="derived_literature",
            purpose="Summarize reference ancestry by field, venue, time span, and high-impact papers.",
            input_schema=_schema({"paper_id": {"type": "string"}}, ["paper_id"]),
            output_schema=_schema({"summary": {"type": "object"}, "references_sampled": {"type": "integer"}}, ["summary"]),
            input_example={"paper_id": "ARXIV:1706.03762"},
            output_example={"summary": {"top_fields": ["Computer Science"], "year_span": [1997, 2017]}},
            reads=["get_references"],
        ),
        _tool(
            name="get_citations",
            category="semantic_scholar.graph",
            purpose="Fetch papers that cite the seed or candidate paper.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/{paper_id}/citations",
            input_schema=_schema(
                {
                    "paper_id": {"type": "string"},
                    "limit": {"type": "integer"},
                    "offset": {"type": "integer"},
                    "fields": {"type": "string"},
                },
                ["paper_id"],
            ),
            output_schema=_paper_array_output("citations"),
            input_example={"paper_id": "ARXIV:1706.03762", "limit": 100, "fields": "citingPaper.paperId,citingPaper.title,citingPaper.year,citingPaper.abstract,citingPaper.citationCount"},
            output_example={"citations": [{"citingPaper": {"paperId": "...", "title": "BERT: Pre-training of Deep Bidirectional Transformers"}}]},
            reads=["Semantic Scholar citations"],
            fallback_tools=["paper_bulk_search", "google_scholar_cited_by_search"],
        ),
        _tool(
            name="get_influential_citations",
            category="derived_literature",
            purpose="Rank citing papers by influential-citation and citation signals.",
            input_schema=_schema({"paper_id": {"type": "string"}, "limit": {"type": "integer"}}, ["paper_id"]),
            output_schema=_paper_array_output("citations"),
            input_example={"paper_id": "ARXIV:1706.03762", "limit": 25},
            output_example={"citations": [{"paperId": "...", "score_reason": "high influentialCitationCount"}]},
            reads=["get_citations"],
        ),
        _tool(
            name="get_recent_citations",
            category="derived_literature",
            purpose="Find recent citing papers that indicate current descendants and future work.",
            input_schema=_schema({"paper_id": {"type": "string"}, "from_year": {"type": "integer"}, "limit": {"type": "integer"}}, ["paper_id", "from_year"]),
            output_schema=_paper_array_output("citations"),
            input_example={"paper_id": "ARXIV:1706.03762", "from_year": 2023, "limit": 50},
            output_example={"citations": [{"paperId": "...", "year": 2025}]},
            reads=["get_citations", "paper_bulk_search"],
        ),
        _tool(
            name="get_citation_timeline",
            category="derived_literature",
            purpose="Group citing papers by year to show whether the topic is active or fading.",
            input_schema=_schema({"paper_id": {"type": "string"}}, ["paper_id"]),
            output_schema=_schema({"timeline": {"type": "object"}, "sample_size": {"type": "integer"}}, ["timeline"]),
            input_example={"paper_id": "ARXIV:1706.03762"},
            output_example={"timeline": {"2018": 120, "2025": 900}},
            reads=["get_citations"],
        ),
        _tool(
            name="get_citation_field_spread",
            category="derived_literature",
            purpose="Summarize which fields and communities cite the seed paper.",
            input_schema=_schema({"paper_id": {"type": "string"}}, ["paper_id"]),
            output_schema=_schema({"fields": {"type": "object"}, "sample_size": {"type": "integer"}}, ["fields"]),
            input_example={"paper_id": "ARXIV:1706.03762"},
            output_example={"fields": {"Computer Science": 950, "Medicine": 20}},
            reads=["get_citations"],
        ),
        _tool(
            name="paper_bulk_search",
            category="semantic_scholar.search",
            purpose="Run high-recall paper search with filters, sorting, and token pagination.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/search/bulk",
            input_schema=_schema(
                {
                    "query": {"type": "string"},
                    "year": {"type": "string"},
                    "publicationDateOrYear": {"type": "string"},
                    "venue": {"type": "string"},
                    "fieldsOfStudy": {"type": "string"},
                    "publicationTypes": {"type": "string"},
                    "openAccessPdf": {"type": "boolean"},
                    "minCitationCount": {"type": "integer"},
                    "sort": {"type": "string"},
                    "limit": {"type": "integer"},
                    "token": {"type": ["string", "null"]},
                    "fields": {"type": "string"},
                },
                ["query"],
            ),
            output_schema=_paper_array_output("papers"),
            input_example={"query": '"transformer" + "machine translation"', "year": "2017-", "sort": "citationCount:desc", "limit": 50, "fields": PAPER_FIELDS},
            output_example={"papers": [{"paperId": "...", "title": "..."}], "next_token": "abc"},
            reads=["Semantic Scholar bulk search"],
            fallback_tools=["paper_relevance_search", "google_scholar_search"],
            notes=["Use for recall. Query searches title/abstract words and supports phrases, required terms, exclusions, OR, and grouping."],
        ),
        _tool(
            name="paper_relevance_search",
            category="semantic_scholar.search",
            purpose="Run precision-oriented ranked search for a small set of highly relevant papers.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/search",
            input_schema=_schema({"query": {"type": "string"}, "limit": {"type": "integer"}, "offset": {"type": "integer"}, "fields": {"type": "string"}}, ["query"]),
            output_schema=_paper_array_output("papers"),
            input_example={"query": "sparse autoencoders mechanistic interpretability", "limit": 10, "fields": PAPER_FIELDS},
            output_example={"papers": [{"paperId": "...", "title": "..."}]},
            reads=["Semantic Scholar relevance search"],
            fallback_tools=["paper_bulk_search"],
        ),
        _tool(
            name="generated_query_search",
            category="derived_search",
            purpose="Generate and execute multiple method/task/dataset/claim query families from seed metadata.",
            input_schema=_schema({"seed_paper": {"type": "object"}, "query_families": {"type": "array", "items": {"type": "string"}}, "limit_per_query": {"type": "integer"}}, ["seed_paper"]),
            output_schema=_schema({"queries": {"type": "array"}, "papers": {"type": "array"}, "warnings": {"type": "array"}}, ["queries", "papers"]),
            input_example={"seed_paper": {"title": "Attention is All you Need"}, "query_families": ["method", "task", "survey", "critique"], "limit_per_query": 25},
            output_example={"queries": ['"self-attention" + transformer'], "papers": [{"paperId": "..."}]},
            reads=["paper_bulk_search", "paper_relevance_search"],
        ),
        _tool(
            name="method_name_search",
            category="derived_search",
            purpose="Search exact method names and extensions/limitations around them.",
            input_schema=_schema({"method_name": {"type": "string"}, "modifiers": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}, ["method_name"]),
            output_schema=_paper_array_output("papers"),
            input_example={"method_name": "FlashAttention", "modifiers": ["extension", "limitation", "benchmark"], "limit": 20},
            output_example={"papers": [{"paperId": "...", "query": '"FlashAttention" limitation'}]},
            reads=["paper_bulk_search", "snippet_search", "google_scholar_search"],
        ),
        _tool(
            name="task_search",
            category="derived_search",
            purpose="Search by problem/task rather than method to find competitors and non-citing related work.",
            input_schema=_schema({"task": {"type": "string"}, "from_year": {"type": "integer"}, "limit": {"type": "integer"}}, ["task"]),
            output_schema=_paper_array_output("papers"),
            input_example={"task": "neural machine translation sequence transduction", "from_year": 2015, "limit": 40},
            output_example={"papers": [{"paperId": "...", "relation": "same_task_competitor"}]},
            reads=["paper_bulk_search", "paper_relevance_search"],
        ),
        _tool(
            name="dataset_benchmark_search",
            category="derived_search",
            purpose="Search papers using the same dataset or benchmark for baselines and evaluation context.",
            input_schema=_schema({"dataset_or_benchmark": {"type": "string"}, "method_or_task": {"type": "string"}, "limit": {"type": "integer"}}, ["dataset_or_benchmark"]),
            output_schema=_paper_array_output("papers"),
            input_example={"dataset_or_benchmark": "WMT 2014 English-German", "method_or_task": "machine translation", "limit": 25},
            output_example={"papers": [{"paperId": "...", "relation": "benchmark_context"}]},
            reads=["paper_bulk_search", "google_scholar_search"],
        ),
        _tool(
            name="survey_search",
            category="derived_search",
            purpose="Find surveys, tutorials, reviews, and taxonomies related to the section.",
            input_schema=_schema({"topic": {"type": "string"}, "limit": {"type": "integer"}}, ["topic"]),
            output_schema=_paper_array_output("papers"),
            input_example={"topic": "efficient attention mechanisms", "limit": 20},
            output_example={"papers": [{"paperId": "...", "relation": "survey"}]},
            reads=["paper_bulk_search", "google_scholar_search"],
        ),
        _tool(
            name="critique_limitation_search",
            category="derived_search",
            purpose="Find limitations, failure modes, robustness analyses, critiques, and negative results.",
            input_schema=_schema({"method_or_claim": {"type": "string"}, "limit": {"type": "integer"}}, ["method_or_claim"]),
            output_schema=_paper_array_output("papers"),
            input_example={"method_or_claim": "transformer long context limitation", "limit": 25},
            output_example={"papers": [{"paperId": "...", "relation": "limitation_analysis"}]},
            reads=["paper_bulk_search", "snippet_search", "google_scholar_search"],
        ),
        _tool(
            name="reproducibility_search",
            category="derived_search",
            purpose="Find replications, ablations, benchmarks, and empirical stress tests.",
            input_schema=_schema({"method_or_claim": {"type": "string"}, "dataset": {"type": "string"}, "limit": {"type": "integer"}}, ["method_or_claim"]),
            output_schema=_paper_array_output("papers"),
            input_example={"method_or_claim": "sparse autoencoder interpretability", "dataset": "language model", "limit": 25},
            output_example={"papers": [{"paperId": "...", "relation": "reproducibility"}]},
            reads=["paper_bulk_search", "snippet_search", "google_scholar_search"],
        ),
        _tool(
            name="snippet_search",
            category="semantic_scholar.search",
            purpose="Search paper snippets for direct mentions of claims, limitations, benchmarks, and terminology.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/snippet/search",
            input_schema=_schema({"query": {"type": "string"}, "limit": {"type": "integer"}}, ["query"]),
            output_schema=_schema({"snippets": {"type": "array", "items": {"type": "object"}}, "warnings": {"type": "array", "items": {"type": "string"}}}, ["snippets"]),
            input_example={"query": '"multi-head attention" "limitation"', "limit": 20},
            output_example={"snippets": [{"paperId": "...", "snippet": "..."}]},
            reads=["Semantic Scholar snippet search"],
            fallback_tools=["paper_bulk_search", "google_scholar_search"],
        ),
        _tool(
            name="claim_snippet_search",
            category="derived_search",
            purpose="Generate snippet queries from an extracted claim and collect direct textual evidence.",
            input_schema=_schema({"claim": {"type": "string"}, "limit": {"type": "integer"}}, ["claim"]),
            output_schema=_schema({"queries": {"type": "array"}, "snippets": {"type": "array"}}, ["queries", "snippets"]),
            input_example={"claim": "self-attention improves long-range dependency modeling", "limit": 20},
            output_example={"queries": ['"long-range dependency" "self-attention"'], "snippets": [{"paperId": "..."}]},
            reads=["snippet_search"],
        ),
        _tool(
            name="author_search",
            category="semantic_scholar.author",
            purpose="Resolve ambiguous author names to Semantic Scholar author IDs.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/author/search",
            input_schema=_schema({"query": {"type": "string"}, "limit": {"type": "integer"}, "fields": {"type": "string"}}, ["query"]),
            output_schema=_schema({"authors": {"type": "array", "items": {"type": "object"}}, "warnings": {"type": "array", "items": {"type": "string"}}}, ["authors"]),
            input_example={"query": "Yoshua Bengio", "limit": 5, "fields": "authorId,name,url,paperCount,citationCount,hIndex"},
            output_example={"authors": [{"authorId": "...", "name": "Yoshua Bengio"}]},
            reads=["Semantic Scholar author search"],
        ),
        _tool(
            name="get_author_profile",
            category="semantic_scholar.author",
            purpose="Fetch an author profile with citation and publication metadata.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/author/{author_id}",
            input_schema=_schema({"author_id": {"type": "string"}, "fields": {"type": "string"}}, ["author_id"]),
            output_schema=_schema({"author": {"type": "object"}}, ["author"]),
            input_example={"author_id": "1741101", "fields": "authorId,name,url,paperCount,citationCount,hIndex"},
            output_example={"author": {"authorId": "1741101", "name": "Yoshua Bengio"}},
            reads=["Semantic Scholar author details"],
        ),
        _tool(
            name="get_author_papers",
            category="semantic_scholar.author",
            purpose="Fetch an author's prior and follow-up work for lineage analysis.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/author/{author_id}/papers",
            input_schema=_schema({"author_id": {"type": "string"}, "limit": {"type": "integer"}, "offset": {"type": "integer"}, "fields": {"type": "string"}}, ["author_id"]),
            output_schema=_paper_array_output("papers"),
            input_example={"author_id": "1741101", "limit": 100, "fields": PAPER_FIELDS},
            output_example={"papers": [{"paperId": "...", "title": "..."}]},
            reads=["Semantic Scholar author papers"],
        ),
        _tool(
            name="same_author_prior_work",
            category="derived_literature",
            purpose="Find same-author papers before the seed year that relate to the section.",
            input_schema=_schema({"seed_paper": {"type": "object"}, "section_terms": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}, ["seed_paper"]),
            output_schema=_paper_array_output("papers"),
            input_example={"seed_paper": {"year": 2017, "authors": [{"authorId": "..."}]}, "section_terms": ["attention"], "limit": 20},
            output_example={"papers": [{"paperId": "...", "relation": "same_author_prior"}]},
            reads=["get_author_papers", "rank_candidates_by_specter2_similarity"],
        ),
        _tool(
            name="same_author_followup_work",
            category="derived_literature",
            purpose="Find same-author papers after the seed year that extend or reinterpret the seed.",
            input_schema=_schema({"seed_paper": {"type": "object"}, "section_terms": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}, ["seed_paper"]),
            output_schema=_paper_array_output("papers"),
            input_example={"seed_paper": {"year": 2017, "authors": [{"authorId": "..."}]}, "section_terms": ["transformer"], "limit": 20},
            output_example={"papers": [{"paperId": "...", "relation": "same_author_followup"}]},
            reads=["get_author_papers", "rank_candidates_by_specter2_similarity"],
        ),
        _tool(
            name="batch_get_papers",
            category="semantic_scholar.graph",
            purpose="Enrich many candidate paper IDs in one request, optionally including SPECTER2 embeddings.",
            endpoint="POST https://api.semanticscholar.org/graph/v1/paper/batch",
            input_schema=_schema({"ids": {"type": "array", "items": {"type": "string"}}, "fields": {"type": "string"}}, ["ids"]),
            output_schema=_schema({"papers": {"type": "array", "items": {"type": ["object", "null"]}}, "warnings": {"type": "array", "items": {"type": "string"}}}, ["papers"]),
            input_example={"ids": ["ARXIV:1706.03762", "ARXIV:1810.04805"], "fields": PAPER_FIELDS_WITH_EMBEDDING},
            output_example={"papers": [{"paperId": "...", "embedding": {"model": "specter_v2", "vector": [0.01]}}]},
            reads=["Semantic Scholar batch paper details"],
            notes=["Prefer batch lookup over one call per candidate."],
        ),
        _tool(
            name="batch_get_authors",
            category="semantic_scholar.author",
            purpose="Fetch many author profiles in one request.",
            endpoint="POST https://api.semanticscholar.org/graph/v1/author/batch",
            input_schema=_schema({"ids": {"type": "array", "items": {"type": "string"}}, "fields": {"type": "string"}}, ["ids"]),
            output_schema=_schema({"authors": {"type": "array", "items": {"type": ["object", "null"]}}}, ["authors"]),
            input_example={"ids": ["1741101"], "fields": "authorId,name,url,paperCount,citationCount,hIndex"},
            output_example={"authors": [{"authorId": "1741101", "name": "Yoshua Bengio"}]},
            reads=["Semantic Scholar batch author details"],
        ),
        _tool(
            name="paper_autocomplete",
            category="semantic_scholar.search",
            purpose="Resolve incomplete/noisy paper titles.",
            endpoint="GET https://api.semanticscholar.org/graph/v1/paper/autocomplete",
            input_schema=_schema({"query": {"type": "string"}, "limit": {"type": "integer"}}, ["query"]),
            output_schema=_schema({"matches": {"type": "array", "items": {"type": "object"}}}, ["matches"]),
            input_example={"query": "Attention is all", "limit": 10},
            output_example={"matches": [{"paperId": "...", "title": "Attention is All you Need"}]},
            reads=["Semantic Scholar autocomplete"],
        ),
        _tool(
            name="list_dataset_releases",
            category="semantic_scholar.datasets",
            purpose="List downloadable Semantic Scholar dataset release IDs.",
            endpoint="GET https://api.semanticscholar.org/datasets/v1/release",
            input_schema=_schema({}, []),
            output_schema=_schema({"releases": {"type": "array", "items": {"type": "string"}}}, ["releases"]),
            input_example={},
            output_example={"releases": ["2026-04-21"]},
            reads=["Semantic Scholar datasets"],
        ),
        _tool(
            name="list_datasets_in_release",
            category="semantic_scholar.datasets",
            purpose="List dataset names available inside a release.",
            endpoint="GET https://api.semanticscholar.org/datasets/v1/release/{release_id}",
            input_schema=_schema({"release_id": {"type": "string"}}, ["release_id"]),
            output_schema=_schema({"datasets": {"type": "array", "items": {"type": "object"}}}, ["datasets"]),
            input_example={"release_id": "latest"},
            output_example={"datasets": [{"name": "papers"}, {"name": "embeddings"}]},
            reads=["Semantic Scholar datasets"],
        ),
        _tool(
            name="get_dataset_download_links",
            category="semantic_scholar.datasets",
            purpose="Get signed links for a Semantic Scholar bulk dataset snapshot.",
            endpoint="GET https://api.semanticscholar.org/datasets/v1/release/{release_id}/dataset/{dataset_name}",
            input_schema=_schema({"release_id": {"type": "string"}, "dataset_name": {"type": "string"}}, ["release_id", "dataset_name"]),
            output_schema=_schema({"files": {"type": "array", "items": {"type": "string"}}}, ["files"]),
            input_example={"release_id": "latest", "dataset_name": "papers"},
            output_example={"files": ["https://..."]},
            reads=["Semantic Scholar datasets"],
            notes=["Use only for offline/local graph construction, not ordinary per-run research."],
        ),
        _tool(
            name="rank_candidates_by_specter2_similarity",
            category="derived_embedding",
            purpose="Compute cosine similarity from seed SPECTER2 embedding to candidate embeddings.",
            input_schema=_schema({"seed_paper_id": {"type": "string"}, "candidate_paper_ids": {"type": "array", "items": {"type": "string"}}, "bucket": {"type": "string"}}, ["seed_paper_id", "candidate_paper_ids"]),
            output_schema=_schema({"ranked_candidates": {"type": "array", "items": {"type": "object"}}, "missing_embeddings": {"type": "array", "items": {"type": "string"}}}, ["ranked_candidates"]),
            input_example={"seed_paper_id": "ARXIV:1706.03762", "candidate_paper_ids": ["ARXIV:1810.04805"], "bucket": "recent_followups"},
            output_example={"ranked_candidates": [{"paperId": "...", "semantic_similarity": 0.82}]},
            reads=["batch_get_papers"],
            fallback_tools=["paper_bulk_search"],
            notes=["Rerank inside literature buckets; do not collapse all relation types into one list."],
        ),
        _tool(
            name="cluster_related_papers",
            category="derived_embedding",
            purpose="Cluster candidate papers into literature themes using embeddings and titles/abstracts.",
            input_schema=_schema({"candidate_paper_ids": {"type": "array", "items": {"type": "string"}}, "target_cluster_count": {"type": "integer"}}, ["candidate_paper_ids"]),
            output_schema=_schema({"clusters": {"type": "array", "items": {"type": "object"}}, "unclustered": {"type": "array"}}, ["clusters"]),
            input_example={"candidate_paper_ids": ["..."], "target_cluster_count": 6},
            output_example={"clusters": [{"label": "efficient attention variants", "paper_ids": ["..."]}]},
            reads=["batch_get_papers"],
        ),
        _tool(
            name="find_nearest_non_citing_papers",
            category="derived_embedding",
            purpose="Find semantically close papers that do not cite and are not cited by the seed.",
            input_schema=_schema({"seed_paper_id": {"type": "string"}, "candidate_query": {"type": "string"}, "limit": {"type": "integer"}}, ["seed_paper_id", "candidate_query"]),
            output_schema=_paper_array_output("papers"),
            input_example={"seed_paper_id": "ARXIV:1706.03762", "candidate_query": '"sequence transduction" "attention"', "limit": 25},
            output_example={"papers": [{"paperId": "...", "semantic_similarity": 0.79, "relation": "non_citing_similar"}]},
            reads=["paper_bulk_search", "get_citations", "get_references", "rank_candidates_by_specter2_similarity"],
        ),
        _tool(
            name="novelty_neighbor_search",
            category="derived_embedding",
            purpose="Find closest pre-seed neighbors for novelty comparison.",
            input_schema=_schema({"seed_paper_id": {"type": "string"}, "seed_year": {"type": "integer"}, "queries": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}, ["seed_paper_id", "seed_year"]),
            output_schema=_paper_array_output("papers"),
            input_example={"seed_paper_id": "ARXIV:1706.03762", "seed_year": 2017, "queries": ['"self-attention" "sequence transduction"'], "limit": 20},
            output_example={"papers": [{"paperId": "...", "year": 2016, "semantic_similarity": 0.81}]},
            reads=["get_references", "paper_bulk_search", "rank_candidates_by_specter2_similarity"],
        ),
        _tool(
            name="build_literature_context_pack",
            category="derived_literature",
            purpose="Build the full structured literature bundle for an arXiv paper.",
            input_schema=_schema({"arxiv_url": {"type": "string"}, "section_terms": {"type": "array", "items": {"type": "string"}}, "limits": {"type": "object"}}, ["arxiv_url"]),
            output_schema=_schema({"context_pack": {"type": "object"}, "warnings": {"type": "array"}}, ["context_pack"]),
            input_example={"arxiv_url": "https://arxiv.org/abs/1706.03762", "section_terms": ["self-attention"], "limits": {"per_bucket": 25}},
            output_example={"context_pack": {"seed": {"paperId": "..."}, "closest_prior_work": [], "recent_followups": []}},
            reads=["resolve_arxiv_paper", "get_references", "get_citations", "generated_query_search", "same_author_prior_work", "same_author_followup_work", "rank_candidates_by_specter2_similarity"],
        ),
        _tool(
            name="classify_related_paper_role",
            category="derived_literature",
            purpose="Label why a candidate paper matters relative to the seed.",
            input_schema=_schema({"seed": {"type": "object"}, "candidate": {"type": "object"}, "relation_sources": {"type": "array", "items": {"type": "string"}}}, ["seed", "candidate"]),
            output_schema=_schema({"role": {"type": "string"}, "confidence": {"type": "number"}, "reason": {"type": "string"}}, ["role", "confidence", "reason"]),
            input_example={"seed": {"title": "..."}, "candidate": {"title": "..."}, "relation_sources": ["citation", "bulk_search:method"]},
            output_example={"role": "METHOD_EXTENSION", "confidence": 0.83, "reason": "Cites seed and modifies the same architecture component."},
            reads=["paper metadata and relation labels"],
        ),
        _tool(
            name="extract_research_gap_candidates",
            category="derived_synthesis",
            purpose="Extract evidence-backed research gaps from context packs, limitations, surveys, and critiques.",
            input_schema=_schema({"context_pack": {"type": "object"}, "section_question": {"type": "string"}}, ["context_pack", "section_question"]),
            output_schema=_schema({"gaps": {"type": "array", "items": {"type": "object"}}}, ["gaps"]),
            input_example={"context_pack": {"critiques_limitations": []}, "section_question": "long-context attention"},
            output_example={"gaps": [{"gap": "...", "supporting_papers": ["..."], "evidence_type": "survey/open-problem"}]},
            reads=["context pack artifacts"],
        ),
        _tool(
            name="novelty_comparison_table",
            category="derived_synthesis",
            purpose="Compare the seed against closest prior work across problem, method, assumptions, evaluation, and limitations.",
            input_schema=_schema({"seed": {"type": "object"}, "prior_papers": {"type": "array", "items": {"type": "object"}}}, ["seed", "prior_papers"]),
            output_schema=_schema({"table_markdown": {"type": "string"}, "weak_claims": {"type": "array"}}, ["table_markdown"]),
            input_example={"seed": {"title": "..."}, "prior_papers": [{"title": "..."}]},
            output_example={"table_markdown": "| axis | seed | prior |\\n|---|---|---|", "weak_claims": []},
            reads=["context pack artifacts"],
        ),
        _tool(
            name="citation_path_finder",
            category="derived_graph",
            purpose="Find direct citation, shared-reference, shared-citation, co-citation, or same-author paths between papers.",
            input_schema=_schema({"seed_paper_id": {"type": "string"}, "candidate_paper_id": {"type": "string"}, "max_depth": {"type": "integer"}}, ["seed_paper_id", "candidate_paper_id"]),
            output_schema=_schema({"paths": {"type": "array", "items": {"type": "object"}}, "scores": {"type": "object"}}, ["paths"]),
            input_example={"seed_paper_id": "...", "candidate_paper_id": "...", "max_depth": 2},
            output_example={"paths": [{"type": "shared_reference", "paper_ids": ["..."]}]},
            reads=["get_references", "get_citations"],
        ),
        _tool(
            name="shared_references",
            category="derived_graph",
            purpose="Find overlapping references between two papers.",
            input_schema=_schema({"paper_id_a": {"type": "string"}, "paper_id_b": {"type": "string"}}, ["paper_id_a", "paper_id_b"]),
            output_schema=_schema({"shared_references": {"type": "array"}, "score": {"type": "number"}}, ["shared_references", "score"]),
            input_example={"paper_id_a": "...", "paper_id_b": "..."},
            output_example={"shared_references": [{"paperId": "..."}], "score": 0.21},
            reads=["get_references"],
        ),
        _tool(
            name="shared_citations",
            category="derived_graph",
            purpose="Find later papers that cite both papers.",
            input_schema=_schema({"paper_id_a": {"type": "string"}, "paper_id_b": {"type": "string"}}, ["paper_id_a", "paper_id_b"]),
            output_schema=_schema({"shared_citations": {"type": "array"}, "score": {"type": "number"}}, ["shared_citations", "score"]),
            input_example={"paper_id_a": "...", "paper_id_b": "..."},
            output_example={"shared_citations": [{"paperId": "..."}], "score": 0.12},
            reads=["get_citations"],
        ),
        _tool(
            name="bibliographic_coupling_score",
            category="derived_graph",
            purpose="Score relatedness based on shared references.",
            input_schema=_schema({"paper_id_a": {"type": "string"}, "paper_id_b": {"type": "string"}}, ["paper_id_a", "paper_id_b"]),
            output_schema=_schema({"score": {"type": "number"}, "shared_count": {"type": "integer"}}, ["score", "shared_count"]),
            input_example={"paper_id_a": "...", "paper_id_b": "..."},
            output_example={"score": 0.34, "shared_count": 12},
            reads=["shared_references"],
        ),
        _tool(
            name="co_citation_score",
            category="derived_graph",
            purpose="Score relatedness based on shared citing papers.",
            input_schema=_schema({"paper_id_a": {"type": "string"}, "paper_id_b": {"type": "string"}}, ["paper_id_a", "paper_id_b"]),
            output_schema=_schema({"score": {"type": "number"}, "shared_count": {"type": "integer"}}, ["score", "shared_count"]),
            input_example={"paper_id_a": "...", "paper_id_b": "..."},
            output_example={"score": 0.18, "shared_count": 23},
            reads=["shared_citations"],
        ),
        _tool(
            name="field_distribution",
            category="derived_literature",
            purpose="Analyze field spread across seed, references, citations, and search candidates.",
            input_schema=_schema({"papers": {"type": "array", "items": {"type": "object"}}, "group_by": {"type": "string"}}, ["papers"]),
            output_schema=_schema({"distribution": {"type": "object"}}, ["distribution"]),
            input_example={"papers": [{"s2FieldsOfStudy": []}], "group_by": "source_bucket"},
            output_example={"distribution": {"recent_followups": {"Computer Science": 30}}},
            reads=["context pack artifacts"],
        ),
        _tool(
            name="venue_distribution",
            category="derived_literature",
            purpose="Analyze venue spread across references, citations, and search candidates.",
            input_schema=_schema({"papers": {"type": "array", "items": {"type": "object"}}, "group_by": {"type": "string"}}, ["papers"]),
            output_schema=_schema({"distribution": {"type": "object"}}, ["distribution"]),
            input_example={"papers": [{"venue": "NeurIPS"}], "group_by": "source_bucket"},
            output_example={"distribution": {"references": {"NeurIPS": 7}}},
            reads=["context pack artifacts"],
        ),
        _tool(
            name="past_related_work_window",
            category="derived_search",
            purpose="Search for related work before or at seed publication for novelty baselines.",
            input_schema=_schema({"query": {"type": "string"}, "seed_year": {"type": "integer"}, "limit": {"type": "integer"}}, ["query", "seed_year"]),
            output_schema=_paper_array_output("papers"),
            input_example={"query": '"sequence transduction" "attention"', "seed_year": 2017, "limit": 25},
            output_example={"papers": [{"paperId": "...", "year": 2016}]},
            reads=["paper_bulk_search", "novelty_neighbor_search"],
        ),
        _tool(
            name="near_publication_related_work",
            category="derived_search",
            purpose="Search contemporaneous work around seed publication for parallel discoveries.",
            input_schema=_schema({"query": {"type": "string"}, "seed_year": {"type": "integer"}, "window_years": {"type": "integer"}, "limit": {"type": "integer"}}, ["query", "seed_year"]),
            output_schema=_paper_array_output("papers"),
            input_example={"query": '"self-attention"', "seed_year": 2017, "window_years": 2, "limit": 25},
            output_example={"papers": [{"paperId": "...", "year": 2017}]},
            reads=["paper_bulk_search"],
        ),
        _tool(
            name="future_related_work_window",
            category="derived_search",
            purpose="Search post-seed related work for extensions, critiques, and impact.",
            input_schema=_schema({"query": {"type": "string"}, "seed_year": {"type": "integer"}, "limit": {"type": "integer"}}, ["query", "seed_year"]),
            output_schema=_paper_array_output("papers"),
            input_example={"query": '"multi-head attention" limitation', "seed_year": 2017, "limit": 25},
            output_example={"papers": [{"paperId": "...", "year": 2020}]},
            reads=["paper_bulk_search", "get_citations"],
        ),
        _tool(
            name="recent_state_of_field",
            category="derived_search",
            purpose="Search recent work only to understand current field state.",
            input_schema=_schema({"query": {"type": "string"}, "from_year": {"type": "integer"}, "limit": {"type": "integer"}}, ["query", "from_year"]),
            output_schema=_paper_array_output("papers"),
            input_example={"query": '"efficient attention" survey', "from_year": 2023, "limit": 30},
            output_example={"papers": [{"paperId": "...", "year": 2025}]},
            reads=["paper_bulk_search", "google_scholar_search"],
        ),
        _tool(
            name="google_scholar_search",
            category="serpapi.google_scholar",
            purpose="Search Google Scholar via SerpApi for metadata, snippets, PDFs, cited-by IDs, and related pages.",
            endpoint="GET https://serpapi.com/search?engine=google_scholar",
            input_schema=_schema(
                {
                    "query": {"type": "string"},
                    "start": {"type": "integer"},
                    "num": {"type": "integer"},
                    "as_ylo": {"type": "integer"},
                    "as_yhi": {"type": "integer"},
                    "scisbd": {"type": "integer"},
                    "cites": {"type": "string"},
                    "cluster": {"type": "string"},
                },
                ["query"],
            ),
            output_schema=_schema({"organic_results": {"type": "array", "items": {"type": "object"}}, "search_information": {"type": "object"}, "citations_per_year": {"type": "array"}}, ["organic_results"]),
            input_example={"query": '"Attention is All you Need" limitations', "num": 10, "as_ylo": 2020},
            output_example={"organic_results": [{"title": "...", "snippet": "...", "inline_links": {"cited_by": {"cites_id": "..."}}}]},
            reads=["SerpApi Google Scholar"],
            fallback_tools=["paper_bulk_search"],
            notes=["Use for corroboration and discovery, not canonical metadata."],
        ),
        _tool(
            name="google_scholar_cited_by_search",
            category="serpapi.google_scholar",
            purpose="Use a Google Scholar cites ID to search citing documents.",
            endpoint="GET https://serpapi.com/search?engine=google_scholar&cites={cites_id}",
            input_schema=_schema({"cites_id": {"type": "string"}, "query": {"type": "string"}, "num": {"type": "integer"}, "as_ylo": {"type": "integer"}}, ["cites_id"]),
            output_schema=_schema({"organic_results": {"type": "array", "items": {"type": "object"}}}, ["organic_results"]),
            input_example={"cites_id": "8089228236537804015", "query": "limitations", "num": 10},
            output_example={"organic_results": [{"title": "..."}]},
            reads=["SerpApi Google Scholar cited-by search"],
        ),
        _tool(
            name="google_scholar_related_pages_search",
            category="serpapi.google_scholar",
            purpose="Use Google Scholar related-pages/cluster signals for discovery outside Semantic Scholar.",
            endpoint="GET https://serpapi.com/search?engine=google_scholar&cluster={cluster_id}",
            input_schema=_schema({"cluster_id": {"type": "string"}, "num": {"type": "integer"}}, ["cluster_id"]),
            output_schema=_schema({"organic_results": {"type": "array", "items": {"type": "object"}}}, ["organic_results"]),
            input_example={"cluster_id": "8089228236537804015", "num": 10},
            output_example={"organic_results": [{"title": "..."}]},
            reads=["SerpApi Google Scholar cluster search"],
        ),
        _tool(
            name="google_scholar_cite_formats",
            category="serpapi.google_scholar",
            purpose="Fetch citation formats and BibTeX links for a Scholar result when needed for reference cleanup.",
            endpoint="GET https://serpapi.com/search?engine=google_scholar_cite",
            input_schema=_schema({"result_id": {"type": "string"}}, ["result_id"]),
            output_schema=_schema({"citations": {"type": "array"}, "links": {"type": "array"}}, ["citations", "links"]),
            input_example={"result_id": "7zTl-Ti2QnAJ"},
            output_example={"citations": [{"title": "MLA", "snippet": "..."}], "links": [{"name": "BibTeX"}]},
            reads=["SerpApi Google Scholar Cite"],
        ),
        _tool(
            name="read_workspace_file",
            category="workspace",
            purpose="Read a markdown or JSON artifact from an allowed workspace path.",
            input_schema=_schema({"path": {"type": "string"}, "start_line": {"type": "integer"}, "end_line": {"type": "integer"}}, ["path"]),
            output_schema=_schema({"content": {"type": "string"}, "line_count": {"type": "integer"}}, ["content"]),
            input_example={"path": "memory.md", "start_line": 1, "end_line": 120},
            output_example={"content": "# Memory\\n...", "line_count": 45},
            reads=["own workspace", "shared read-only run artifacts"],
        ),
        _tool(
            name="write_workspace_markdown",
            category="workspace",
            purpose="Create or replace a markdown artifact in the caller's owned workspace.",
            input_schema=_schema({"path": {"type": "string"}, "content": {"type": "string"}}, ["path", "content"]),
            output_schema=_schema({"path": {"type": "string"}}, ["path"]),
            input_example={"path": "papers.md", "content": "# Papers\\n"},
            output_example={"path": "papers.md"},
            writes=["own workspace only"],
        ),
        _tool(
            name="append_workspace_markdown",
            category="workspace",
            purpose="Append a dated note, finding, or memory entry to a markdown artifact.",
            input_schema=_schema({"path": {"type": "string"}, "heading": {"type": "string"}, "content": {"type": "string"}}, ["path", "content"]),
            output_schema=_schema({"path": {"type": "string"}}, ["path"]),
            input_example={"path": "memory.md", "heading": "Query: exact title", "content": "Found 12 results."},
            output_example={"path": "memory.md"},
            writes=["own workspace only"],
        ),
        _tool(
            name="patch_workspace_file",
            category="workspace",
            purpose="Patch specific lines in an owned markdown/JSON workspace artifact.",
            input_schema=_schema({"path": {"type": "string"}, "start_line": {"type": "integer"}, "end_line": {"type": "integer"}, "replacement": {"type": "string"}}, ["path", "start_line", "end_line", "replacement"]),
            output_schema=_schema({"path": {"type": "string"}, "changed": {"type": "boolean"}}, ["path", "changed"]),
            input_example={"path": "papers.md", "start_line": 8, "end_line": 10, "replacement": "- corrected paper metadata"},
            output_example={"path": "papers.md", "changed": True},
            reads=["own workspace"],
            writes=["own workspace only"],
            notes=["Use this for precise cleanup instead of rewriting large artifacts blindly."],
        ),
    ]
    return {spec.name: spec for spec in specs}
